# Generated by Django 5.0 on 2023-12-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('comments', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsResgister',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('signup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
